### ISSUE TITLE
Connector.h's post validation

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#21]
Connector.h is lacking pre curl validation of the URL or JSON. 
With an invalid URL the curl post will fail, almost acting as its own validation, however with a valid url the post will succeed no mater the input for JSON.

I don't know much about the server code, but currently it seems that 
with trash input, there is an Internal server error;
and with JSON formatted trash input, It returns an application html error page;

I don't know if this is what we want, because It seems we would want to inform the user as to the specific source of their errors. Something that pre curl JSON validation could provide.

**Comment by krs-world** [comment]
I believe we have talked about testing the url coming from the client. Since Bridges controls the url  (user only sets t he assignment number, etc, which gets checked( need to make sure these are valid); the JSON is completely controlled
by BRIDGES,  not the user. So if the JSON has an issue, we have a bug in BRIDGES. At least on teh C++ side, I have tried to make this piece of code as robust as possible -- the Java side should be similar and we have not had this issue in the past. We have also talked about server catching these kinds of 
errors and sending this back to the client.

We will keep this issue open for now.
