### ISSUE TITLE
Element.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#41]
I combined Element Visualizer and Element.
Removed opacity as Color will handle transparency
Holds map objects not pointers
As the unique id was only used for mapping in JSON creation, I just used its already unique memory address for mapping and deleted unique id. 
Made getRepresentation virtual so polymorphism would work with BSTElement

**Comment by krs-world** [comment]
I am not sure about mixing the visualizer objects with the Element 
classes (both Element visualizer
and Link visualizer. This will also cause differences with teh Java 
implementation..  lets keep these
separate..

I would suggest focus on teh smaller changes rather than these.. wait on 
these till the mid Dec. when
I return.

     --krs


On 12/6/15 3:06 AM, Dakota Carmer wrote:
>
> I combined Element Visualizer and Element.
> Removed opacity as Color will handle transparency
> Holds map objects not pointers
> As the unique id was only used for mapping in JSON creation, I just 
> used its already unique memory address for mapping and deleted unique id.
> Made getRepresentation virtual so polymorphism would work with BSTElement
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/krs-world/bridges-cxx/issues/41>.
>

-- 
Kalpathi Subramanian                                   Ph: 704 687 8579
Associate Professor                                    Email: krs@uncc.edu
Dept of Computer Science                               Web:http://webpages.uncc.edu/~krs
The University of North Carolina
Charlotte, NC 28202-0001

**Comment by esaule** [comment]
I don't understand this issue. Doesn't seem to report an actual issue. As such, closing.
