### ISSUE TITLE
Bridges - static object.

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#48]
I see the reasoning behind this; again, to make the C++ and Java a little more uniform. We should perhaps use new to create the BRIDGES object and use pointers in the driver program. The visualize() and setDataStructure() require pointers anyway. I slightly favor this approach, though there is only one BRIDGES object ever.

Think over this and we can decide. The goal is to make the 2 versions of BRIDGES as close as possible.

**Comment by dcarmer** [comment]
I agree we should make the C++ and Java more consistent on this point, but I believe we should change the Java version to conform to the C++ in this case. Because there is only ever supposed to be one BRIDGES object, it only makes sense to structure it as such, for both clarity and efficiency reasons. In C++ I achieved this effect by turning BRIDGES into a namespace. But the concept lends it self even more directly to Java's concept of static classes, which is what we should modify the Java side to.

To this end, everything in Java must be declared with "new" because there is no other option. While in C++, most programmers avoid using new when possible, as it requires more advanced memory management and quickly can become prone to leaks. In my opinion the gain of creating a more uniform implementation at the cost of performance and maintainability won't be worth it.

Additionally there are numerous multi-language libraries out there already, that while they maintain a semblance of uniformity, they also differ in significant ways, to accommodate each language and users are prepared for this. I don't see students often transitioning from one language of BRIDGES to another and from my perspective even if they did it would only be natural there'd be lingual differences.

I also don't understand what you mean when you say the visualize() and setDataStructure() require pointers. The setDataStructure() takes one in as a parameter, but this can be passes just as easily with the address operator on an object created without "new".

**Comment by esaule** [comment]
Seems fine.
